# Generated by Django 4.2.4 on 2023-08-09 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('aboutImage', models.ImageField(upload_to='about_image')),
                ('aboutCv', models.FileField(upload_to='cv')),
                ('aboutDescription', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('icon', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('institute_name', models.CharField(max_length=100)),
                ('institute_logo', models.ImageField(upload_to='education_training')),
                ('course_title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('companyLogo', models.ImageField(upload_to='company_logo')),
                ('designation', models.CharField(max_length=100)),
                ('responsibility', models.TextField(max_length=300)),
                ('start_date', models.DateField(default=datetime.timezone)),
                ('end_date', models.DateField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('fatherName', models.CharField(max_length=100)),
                ('motherName', models.CharField(max_length=100)),
                ('bgImage', models.ImageField(upload_to='bg_image')),
                ('skill_ease', models.TextField(max_length=500)),
                ('contact_image', models.ImageField(upload_to='contact_image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('peoject_logo', models.ImageField(upload_to='project_image')),
                ('project_duration', models.IntegerField(blank=True)),
                ('repository', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, default=None)),
                ('end_date', models.DateField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('skill_title', models.CharField(max_length=50)),
                ('knowledge_percent', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
