# Generated by Django 4.2.4 on 2023-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0002_alter_aboutinfo_aboutdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='aboutDescription',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='introinfo',
            name='skill_ease',
            field=models.TextField(max_length=3000),
        ),
    ]
