# Generated by Django 4.2.4 on 2023-08-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0003_alter_aboutinfo_aboutdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationtraining',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experienceinfo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='introinfo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectsinfo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skillinfo',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
