# Generated by Django 4.2.4 on 2023-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0004_aboutinfo_publish_contactinfo_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceinfo',
            name='companyName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='project_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
