# Generated by Django 4.2.4 on 2023-08-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0005_experienceinfo_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsinfo',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='project_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
