# Generated by Django 4.2.4 on 2023-08-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0006_alter_projectsinfo_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinfo',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='end_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='projectsinfo',
            name='start_date',
            field=models.DateField(default=None),
        ),
    ]
