# Generated by Django 4.2.4 on 2023-08-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0007_alter_experienceinfo_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinfo',
            name='companyLogo',
            field=models.ImageField(blank=True, upload_to='company_logo'),
        ),
    ]
