# Generated by Django 4.2.4 on 2023-08-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0008_alter_experienceinfo_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceinfo',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
