# Generated by Django 4.2.4 on 2023-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morshed_portfolio', '0010_alter_educationtraining_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsinfo',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
